Repository wjdehrbs/SangbuSanzo, pull requests merged in 2023-08, with the labels that each got.

#29 [DESIGN] Image Resolutions
  app/src/main/res/drawable-hdpi/icon_apeach.png
  app/src/main/res/drawable-hdpi/icon_con.png
  app/src/main/res/drawable-hdpi/icon_lion.png
  app/src/main/res/drawable-hdpi/icon_muji.png
  app/src/main/res/drawable-hdpi/icon_tube.png
  app/src/main/res/drawable-hdpi/logo1.png
  app/src/main/res/drawable-hdpi/num1.png
  app/src/main/res/drawable-mdpi/icon_apeach.png
  app/src/main/res/drawable-mdpi/icon_con.png
  app/src/main/res/drawable-mdpi/icon_lion.png
  app/src/main/res/drawable-mdpi/icon_muji.png
  app/src/main/res/drawable-mdpi/icon_tube.png
  app/src/main/res/drawable-mdpi/logo1.png
  app/src/main/res/drawable-mdpi/num1.png
  app/src/main/res/drawable-xhdpi/icon_apeach.png
  app/src/main/res/drawable-xhdpi/icon_con.png
  app/src/main/res/drawable-xhdpi/icon_lion.png
  app/src/main/res/drawable-xhdpi/icon_muji.png
  app/src/main/res/drawable-xhdpi/icon_tube.png
  app/src/main/res/drawable-xhdpi/logo1.png
  app/src/main/res/drawable-xhdpi/num1.png
  app/src/main/res/drawable-xxhdpi/icon_apeach.png
  app/src/main/res/drawable-xxhdpi/icon_con.png
  app/src/main/res/drawable-xxhdpi/icon_lion.png
  app/src/main/res/drawable-xxhdpi/icon_muji.png
  app/src/main/res/drawable-xxhdpi/icon_tube.png
  app/src/main/res/drawable-xxhdpi/logo1.png
  app/src/main/res/drawable-xxhdpi/num1.png
  app/src/main/res/drawable-xxxhdpi/icon_apeach.png
  app/src/main/res/drawable-xxxhdpi/icon_con.png
  app/src/main/res/drawable-xxxhdpi/icon_lion.png
  app/src/main/res/drawable-xxxhdpi/icon_muji.png
  app/src/main/res/drawable-xxxhdpi/icon_tube.png
  app/src/main/res/drawable-xxxhdpi/logo1.png
  app/src/main/res/drawable-xxxhdpi/num1.png
Labels: Design🎨

#31 [FEAT]]all-page
  .idea/vcs.xml
  app/src/main/java/com/example/sangbusanzo/Detailpage.kt
  app/src/main/java/com/example/sangbusanzo/LogInPage.kt
  app/src/main/java/com/example/sangbusanzo/MainPage.kt
  app/src/main/java/com/example/sangbusanzo/My_page.kt
  app/src/main/java/com/example/sangbusanzo/SignInPage.kt
  app/src/main/res/layout/activity_detailpage.xml
  app/src/main/res/layout/activity_detailpage2.xml
Labels: Feature⚙️

#34 [REFACTOR] Main-Page
  app/src/main/java/com/example/sangbusanzo/MainPage.kt
  app/src/main/java/com/example/sangbusanzo/data/TeamMemberData.kt
Labels: Refactor♻️

#36 [FEAT] All
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/sangbusanzo/Detailpage.kt
  app/src/main/java/com/example/sangbusanzo/LogInPage.kt
  app/src/main/java/com/example/sangbusanzo/MainPage.kt
  app/src/main/java/com/example/sangbusanzo/My_page.kt
  app/src/main/java/com/example/sangbusanzo/SignInPage.kt
  app/src/main/java/com/example/sangbusanzo/data/TeamMemberData.kt
  app/src/main/java/com/example/sangbusanzo/testdev/DetailPage.kt
  app/src/main/java/com/example/sangbusanzo/testdev/LogInPage.kt
  app/src/main/java/com/example/sangbusanzo/testdev/MainPage.kt
  app/src/main/java/com/example/sangbusanzo/testdev/MyPage.kt
  app/src/main/java/com/example/sangbusanzo/testdev/SignInPage.kt
  app/src/main/java/com/example/sangbusanzo/testdev/trest
  app/src/main/res/layout/activity_detailpage.xml
  app/src/main/res/layout/activity_log_in_page.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/layout/activity_signinpage.xml
  app/src/main/res/layout/cardview_friend_profile.xml
  app/src/main/res/layout/cardview_main_profile.xml
  app/src/main/res/layout/cardview_notification.xml
  app/src/main/res/values-en-rUS/strings.xml
  app/src/main/res/values/strings.xml
Labels: Feature⚙️
